---
# please keep properties in the alphabetical order

stargate:

  # metrics properties
  # see io.stargate.sgv2.api.common.config.MetricsConfig for all config properties and options
  metrics:
    global-tags:
      module: sgv3-docsapi

quarkus:

  # general app properties
  application:
    name: Stargate Documents API

  # banner for the startup
  banner:
    path: banner/banner.txt

  # HTTP settings
  http:

    # every /v3 path is authenticated by default
    # adapt if changing the authentication mechanism
    auth:
      proactive: false
      permission:
        default:
          paths: /v3/*
          policy: authenticated

  # TODO START remove after 2.0.1 released
  cache:
    caffeine:
      # keyspace cache for the schema management
      keyspace-cache:
        maximum-size: 1000
        expire-after-access: PT5M
        metrics-enabled: true
  grpc:
    # all the clients' setup, only bridge
    clients:
      bridge:
        host: localhost
        port: 8091
        retry: true
        max-hedged-attempts: 0
    dev-mode:
      force-server-start: false.
  # TODO END remove after 2.0.1 released

  # built-in micrometer properties
  micrometer:
    binder:
      http-server:
        # ignore all non-application uris, as well as the custom set
        suppress-non-application-uris: true
        ignore-patterns: /,/metrics,/swagger-ui.*,.*\.html

        # due to the https://github.com/quarkusio/quarkus/issues/24938
        # we need to define uri templating on our own for now
        # note that order is important
        match-patterns: |

  # adapt path of the open api definitions
  smallrye-openapi:
    path: /api/docs/openapi

# TODO START remove after 2.0.1 released
"%dev":

  # disable retries in the data store config and enable fall back
  stargate:
    data-store:
      bridge-fallback-enabled: true

  io:
    stargate:
      sgv2:
        api:
          common:
            properties:
              datastore:
                configuration:
                  DataStorePropertiesConfiguration/fetchSupportedFeatures/Retry/maxRetries: 0
# TODO END remove after 2.0.1 released